name: release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

env:
  PROJECT: mathtomath
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  publish-linux:
    name: Publish for ${{ matrix.target }}
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: sudo apt update
      - run: sudo apt install musl-tools gcc-multilib
      - run: cargo build --target ${{ matrix.target }} --release
      - uses: svenstaro/upload-release-action@v2
        with:
          file: target/${{ matrix.target }}/release/mathtomath
          asset_name: mathtomath-${{ github.ref_name }}-${{ matrix.target }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish-macos:
    name: Publish for x86_64-apple-darwin
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - run: cargo build --target x86_64-apple-darwin --release
      - uses: svenstaro/upload-release-action@v2
        with:
          file: target/x86_64-apple-darwin/release/mathtomath
          asset_name: mathtomath-${{ github.ref_name }}-x86_64-apple-darwin
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish-windows:
    name: Publish for x86_64-pc-windows-msvc
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - run: cargo build --target x86_64-pc-windows-msvc --release
      - uses: svenstaro/upload-release-action@v2
        with:
          file: .\target\x86_64-pc-windows-msvc\release\mathtomath.exe
          asset_name: mathtomath-${{ github.ref_name }}-x86_64-pc-windows-msvc.exe
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
